export const patients = [
  {
    id: 1,
    avatar: "https://i.pravatar.cc/150?img=11",
    firstName: "John",
    lastName: "Smith",
    age: 32,
    gender: "Male",
    blood: "A+",
    phone: "+1 202-555-0145",
    email: "john@gmail.com",
    doctor: "Dr. Ivandro",
    disease: "Diabetes",
    room: "A-203",
    status: "Active",
  },
  {
    id: 2,
    avatar: "https://i.pravatar.cc/150?img=21",
    firstName: "Anna",
    lastName: "Brown",
    age: 25,
    gender: "Female",
    blood: "O-",
    phone: "+1 202-555-0115",
    email: "anna@gmail.com",
    doctor: "Dr. Carlos",
    disease: "Pneumonia",
    room: "B-115",
    status: "Critical",
  },
  {
    id: 3,
    avatar: "https://i.pravatar.cc/150?img=35",
    firstName: "Michael",
    lastName: "Wilson",
    age: 47,
    gender: "Male",
    blood: "B+",
    phone: "+1 202-555-0170",
    email: "michael@gmail.com",
    doctor: "Dr. Emma",
    disease: "Asthma",
    room: "C-405",
    status: "Recovered",
  },
];